version: "2.4"
services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "8385:15672"
  influx:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-beta
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - "8285:9999"
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

volumes:
  influx-data:
    external: true
