name: 'Docker - Branch Imager'

'on':
  push:
    branches-ignore:
      - main

jobs:
  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    if: '!contains(github.event.head_commit.message, ''[skip ci]'')'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: '${{ runner.os }}-14-${{ hashFiles(''**/yarn.lock'') }}'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Copy Configuration
        run: |
          pushd src &&
          cp config.example.ts config.ts &&
          popd
      - name: Build Code
        uses: icrawl/action-tsc@v1
        with:
          build: src
      - name: Upload Microservice bundle to artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: microservice_bundle
          path: dist/

  Github-Package-Registry-Docker:
    name: Publish image to Github Package Registry
    runs-on: ubuntu-latest
    if: >-
      !(contains(github.event.head_commit.message, '[skip ci]')
      ||contains(github.event.head_commit.message, '[skip docker]'))
    needs: Building
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Download build bundle artifact
        uses: actions/download-artifact@v2-preview
        with:
          name: microservice_bundle
          path: dist/
      - name: Get GitHub Branch Name
        run: >-
          echo ::set-env name=GITHUB_BRANCH_NAME::$(echo ${{ github.ref }} | cut
          -c12- | sed -e 's/\/\|_/-/g')
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: pengubot/firebird/firebird
          username: 'Team PenguBot'
          password: '${{ secrets.PENGU_SECRET }}'
          tags: '${{ env.GITHUB_BRANCH_NAME }}'
          registry: docker.pkg.github.com
